Repository zarr-developers/VirtualiZarr, pull requests merged in 2024-12, with the labels that each got.

#323 Refactor dmrpp tests to expose data file path
  virtualizarr/tests/test_readers/test_dmrpp.py
Labels: testing, internals, DMR++

#243 Paths as URIs
  docs/releases.rst
  docs/usage.md
  pyproject.toml
  virtualizarr/backend.py
  virtualizarr/manifests/array.py
  virtualizarr/manifests/manifest.py
  virtualizarr/readers/dmrpp.py
  virtualizarr/readers/fits.py
  virtualizarr/readers/hdf/hdf.py
  virtualizarr/readers/hdf5.py
  virtualizarr/readers/kerchunk.py
  virtualizarr/readers/netcdf3.py
  virtualizarr/readers/tiff.py
  virtualizarr/readers/zarr_v3.py
  virtualizarr/tests/__init__.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_manifests/test_manifest.py
  virtualizarr/tests/test_readers/test_dmrpp.py
  virtualizarr/tests/test_readers/test_kerchunk.py
  virtualizarr/tests/test_writers/test_kerchunk.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/translators/kerchunk.py
  virtualizarr/writers/icechunk.py
  virtualizarr/writers/kerchunk.py
Labels: Kerchunk, internals, DMR++

#313 Add list of previous talks to readme
  README.md
  docs/releases.rst
Labels: documentation

#325 Correct some documentation links to function the public API
  docs/releases.rst
  docs/usage.md
Labels: documentation

#272 Append to icechunk stores
  ci/upstream.yml
  conftest.py
  docs/releases.rst
  examples/append/noaa-cdr-sst.ipynb
  pyproject.toml
  runtime.txt
  virtualizarr/accessor.py
  virtualizarr/codecs.py
  virtualizarr/manifests/array_api.py
  virtualizarr/manifests/utils.py
  virtualizarr/tests/__init__.py
  virtualizarr/tests/test_codecs.py
  virtualizarr/tests/test_writers/test_icechunk.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/writers/icechunk.py
Labels: enhancement, Icechunk :ice_cube:

#331 Add new page with links to example notebooks
  docs/examples.md
  docs/index.md
  docs/releases.rst
Labels: documentation

#332 Release summary for v1.2.0
  docs/releases.rst
Labels: releases

#333 Release guide release notes correction
  docs/contributing.md
Labels: documentation, releases

#337 Improve readme and top-level package description
  README.md
  docs/faq.md
  docs/index.md
  docs/releases.rst
  docs/usage.md
Labels: documentation

#338 Fix group kwarg
  conftest.py
  docs/releases.rst
  virtualizarr/readers/fits.py
  virtualizarr/readers/hdf5.py
  virtualizarr/readers/netcdf3.py
  virtualizarr/readers/tiff.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_integration.py
  virtualizarr/translators/kerchunk.py
Labels: Kerchunk, readers

#344 Legacy->archival
  README.md
  docs/faq.md
  docs/index.md
  docs/usage.md
Labels: documentation

#351 move some kerchunk tests to dedicated test module
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_readers/test_kerchunk.py
Labels: testing

#357 Remove warning when passing indexes=None
  docs/api.rst
  docs/releases.rst
  docs/usage.md
  virtualizarr/readers/common.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_xarray.py
Labels: documentation

#227 Add nbytes property
  docs/api.rst
  docs/releases.rst
  docs/usage.md
  virtualizarr/accessor.py
  virtualizarr/manifests/array.py
  virtualizarr/manifests/manifest.py
  virtualizarr/tests/test_xarray.py
Labels: enhancement

#362 Configure codecov to ignore tests folder
  .github/codecov.yml
  .github/workflows/main.yml
Labels: CI
