Repository zarr-developers/VirtualiZarr, pull requests merged in 2024-11, with the labels that each got.

#282 Remove unused ManifestBackendArray class
  virtualizarr/readers/common.py
Labels: typing

#191 Search for coord_names in separate_coords
  conftest.py
  virtualizarr/readers/common.py
  virtualizarr/tests/test_backend.py
Labels: bug, CF conventions

#284 Bump minimum Xarray dependency to 2024.10.0
  ci/environment.yml
  ci/min-deps.yml
  ci/upstream.yml
  docs/releases.rst
  pyproject.toml
  virtualizarr/readers/common.py
Labels: xarray, dependencies

#286 Dont write _ARRAY_DIMENSIONS to icechunk
  docs/releases.rst
  virtualizarr/tests/test_writers/test_icechunk.py
  virtualizarr/writers/icechunk.py
Labels: Icechunk :ice_cube:

#288 Fix release notes for v1.1.0
  docs/releases.rst
Labels: documentation

#265 dmrpp root and nested group parsing fix
  docs/releases.rst
  virtualizarr/backend.py
  virtualizarr/readers/dmrpp.py
  virtualizarr/tests/test_readers/test_dmrpp.py
Labels: DMR++

#294 Update README.md
  README.md
Labels: documentation

#301 Remove numcodecs specific install
  ci/upstream.yml
Labels: dependencies

#298 Update contributors guide
  docs/contributing.md
  docs/releases.rst
Labels: documentation

#296 Clarify which features are currently available in FAQ
  docs/faq.md
  docs/releases.rst
  virtualizarr/backend.py
  virtualizarr/tests/test_backend.py
Labels: documentation, readers

#300 Fix sphinx warnings
  .readthedocs.yml
  docs/conf.py
  virtualizarr/manifests/manifest.py
Labels: documentation, CI

#304 Update pkg install in docs contribution guide
  docs/contributing.md
  docs/releases.rst
Labels: documentation

#306 Support downstream type checking by including py.typed
  docs/releases.rst
  virtualizarr/py.typed
Labels: typing

#87 Non-kerchunk backend for HDF5/netcdf4 files.
  ci/environment.yml
  ci/min-deps.yml
  ci/upstream.yml
  pyproject.toml
  virtualizarr/backend.py
  virtualizarr/readers/__init__.py
  virtualizarr/readers/hdf/__init__.py
  virtualizarr/readers/hdf/filters.py
  virtualizarr/readers/hdf/hdf.py
  virtualizarr/tests/__init__.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_readers/conftest.py
  virtualizarr/tests/test_readers/test_hdf.py
  virtualizarr/tests/test_readers/test_hdf_filters.py
  virtualizarr/tests/test_readers/test_hdf_integration.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/utils.py
Labels: enhancement, references generation, encoding

#307 Release note for #87
  docs/releases.rst
Labels: documentation

#303 Add status badges to README
  README.md
Labels: documentation

#314 Consolidate hdf reader tests into their own tests module
  virtualizarr/tests/test_readers/test_hdf/test_hdf.py
  virtualizarr/tests/test_readers/test_hdf/test_hdf_filters.py
  virtualizarr/tests/test_readers/test_hdf/test_hdf_integration.py
Labels: testing, internals, readers

#317 Refactor kerchunk reader tests to call open_virtual_dataset
  virtualizarr/tests/test_readers/test_kerchunk.py
Labels: Kerchunk, testing, readers
