Repository zarr-developers/VirtualiZarr, pull requests merged in 2024-10, with the labels that each got.

#252 Fix mypy errors around numpy functions not being strictly type hinted
  virtualizarr/manifests/array_api.py
  virtualizarr/manifests/manifest.py
Labels: typing

#251 Allow `open_virtual_dataset` to read existing Kerchunk references
  .gitignore
  ci/doc.yml
  conftest.py
  docs/releases.rst
  docs/usage.md
  pyproject.toml
  virtualizarr/backend.py
  virtualizarr/manifests/manifest.py
  virtualizarr/readers/kerchunk.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_utils.py
  virtualizarr/utils.py
Labels: Kerchunk, references generation, references formats

#259 Skip tests that require kerchunk
  .github/workflows/min-deps.yml
  ci/min-deps.yml
  pyproject.toml
  virtualizarr/accessor.py
  virtualizarr/manifests/manifest.py
  virtualizarr/readers/kerchunk.py
  virtualizarr/tests/__init__.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_kerchunk.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_readers/test_kerchunk.py
  virtualizarr/tests/test_utils.py
  virtualizarr/tests/test_writers/test_kerchunk.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/writers/kerchunk.py
  virtualizarr/zarr.py
Labels: Kerchunk, dependencies

#260 allow creating references for empty archival datasets
  docs/releases.rst
  virtualizarr/manifests/manifest.py
  virtualizarr/readers/kerchunk.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_manifests/test_manifest.py
  virtualizarr/tests/test_readers/test_kerchunk.py
  virtualizarr/tests/test_writers/test_kerchunk.py
Labels: references generation

#261 Split kerchunk reader up
  docs/releases.rst
  virtualizarr/backend.py
  virtualizarr/manifests/array.py
  virtualizarr/manifests/array_api.py
  virtualizarr/readers/__init__.py
  virtualizarr/readers/common.py
  virtualizarr/readers/dmrpp.py
  virtualizarr/readers/fits.py
  virtualizarr/readers/hdf5.py
  virtualizarr/readers/kerchunk.py
  virtualizarr/readers/netcdf3.py
  virtualizarr/readers/tiff.py
  virtualizarr/readers/zarr.py
  virtualizarr/readers/zarr_v3.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_writers/test_zarr.py
  virtualizarr/translators/__init__.py
  virtualizarr/translators/kerchunk.py
  virtualizarr/utils.py
  virtualizarr/zarr.py
Labels: Kerchunk, references generation, internals

#264 Add CI job for testing upstream versions of dependencies
  .github/workflows/upstream.yml
  ci/upstream.yml
Labels: CI, testing

#256 Add Icechunk Support
  ci/upstream.yml
  conftest.py
  docs/api.rst
  docs/releases.rst
  docs/usage.md
  virtualizarr/accessor.py
  virtualizarr/readers/zarr_v3.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_readers/test_kerchunk.py
  virtualizarr/tests/test_writers/conftest.py
  virtualizarr/tests/test_writers/test_icechunk.py
  virtualizarr/tests/test_writers/test_zarr.py
  virtualizarr/writers/icechunk.py
  virtualizarr/writers/zarr.py
  virtualizarr/zarr.py
Labels: enhancement, zarr-python, references formats, dependencies

#266 FAQ updates
  docs/api.rst
  docs/faq.md
Labels: documentation

#275 Update index.md
  docs/index.md
Labels: documentation
