Repository zarr-developers/VirtualiZarr, pull requests merged in 2024-07, with the labels that each got.

#170 Warn on index creation
  docs/releases.rst
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/xarray.py
Labels: documentation

#164 Update roadmap for v1.0
  README.md
  docs/faq.md
  docs/index.md
  docs/releases.rst
Labels: documentation

#174 Add example of using cftime_variables to usage docs
  docs/releases.rst
  docs/usage.md
Labels: documentation, CF conventions

#181 v1.0 release notes
  docs/releases.rst
Labels: Packaging

#192 Clarify that virtualizarr is a user-level replacement for kerchunk
  README.md
  docs/faq.md
  docs/index.md
Labels: documentation

#187 Extend refspec support to [path] entries (without offset/length)
  virtualizarr/manifests/manifest.py
Labels: Kerchunk

#193 Conformant ZarrV3 codecs and fill values
  docs/releases.rst
  virtualizarr/kerchunk.py
  virtualizarr/tests/__init__.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/tests/test_zarr.py
  virtualizarr/zarr.py
Labels: zarr-python

#196 https access fix
  virtualizarr/tests/test_xarray.py
  virtualizarr/xarray.py
Labels: remote files
