Repository zarr-developers/VirtualiZarr, pull requests merged in 2024-03, with the labels that each got.

#36 CI for running tests
  virtualizarr/.github/workflows/main.yml
  virtualizarr/ci/environment.yml
Labels: CI

#27 Roughout of Sphinx Docs
  .github/workflows/main.yml
  .readthedocs.yml
  ci/doc.yml
  docs/Makefile
  docs/api.md
  docs/conf.py
  docs/dev_status_roadmap.md
  docs/how_it_works.md
  docs/index.md
  docs/installation.md
  docs/make.bat
  docs/usage.md
  pyproject.toml
  virtualizarr/__init__.py
Labels: documentation

#44 Test concat of dimension coordinate not backed by an index
  README.md
  ci/environment.yml
  virtualizarr/tests/test_xarray.py
Labels: xarray

#48 Narrative docs
  README.md
  docs/index.md
  docs/installation.md
  docs/usage.md
Labels: documentation

#50 More narrative docs
  docs/usage.md
Labels: documentation

#52 open_virtual_dataset with and without indexes
  ci/environment.yml
  docs/usage.md
  pyproject.toml
  virtualizarr/tests/test_xarray.py
  virtualizarr/xarray.py
Labels: xarray

#56 API docs
  docs/api.md
  docs/api.rst
  docs/conf.py
  virtualizarr/__init__.py
  virtualizarr/manifests/array.py
  virtualizarr/manifests/manifest.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/xarray.py
Labels: documentation
