Repository zarr-developers/VirtualiZarr, pull requests merged in 2024-05, with the labels that each got.

#45 Write manifests to zarr store
  docs/usage.md
  virtualizarr/manifests/manifest.py
  virtualizarr/tests/test_zarr.py
  virtualizarr/vendor/__init__.py
  virtualizarr/vendor/zarr/LICENSE.txt
  virtualizarr/vendor/zarr/__init__.py
  virtualizarr/vendor/zarr/utils.py
  virtualizarr/xarray.py
  virtualizarr/zarr.py
Labels: zarr-python, zarr-specs

#106 Install xarray from main
  docs/usage.md
  pyproject.toml
Labels: Packaging

#109 Depend on latest version of xarray
  docs/installation.md
  pyproject.toml
Labels: Packaging, xarray

#110 Write to parquet
  docs/usage.md
  pyproject.toml
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_kerchunk.py
  virtualizarr/xarray.py
Labels: references formats

#42 Test fsspec roundtrip
  pyproject.toml
  virtualizarr/tests/test_integration.py
Labels: xarray

#73 Inline loaded variables into kerchunk references
  docs/usage.md
  pyproject.toml
  virtualizarr/kerchunk.py
  virtualizarr/tests/conftest.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_kerchunk.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_zarr.py
  virtualizarr/zarr.py
Labels: enhancement, Kerchunk

#120 Release notes page
  .github/PULL_REQUEST_TEMPLATE.md
  docs/index.md
  docs/releases.rst
Labels: documentation

#127 requires-python = ">=3.10"
  pyproject.toml
Labels: Packaging
