Repository zarr-developers/VirtualiZarr, pull requests merged in 2024-08, with the labels that each got.

#206 Set ZArray default fill_value as NaT for datetime64
  docs/releases.rst
  virtualizarr/tests/test_integration.py
  virtualizarr/zarr.py
Labels: CF conventions

#213 Update static typing
  .github/workflows/main.yml
  .pre-commit-config.yaml
  ci/environment.yml
  pyproject.toml
  virtualizarr/kerchunk.py
  virtualizarr/manifests/array.py
  virtualizarr/manifests/manifest.py
  virtualizarr/tests/test_zarr.py
  virtualizarr/xarray.py
  virtualizarr/zarr.py
Labels: CI

#214 Adds concurrency to CI w/ cancel-in-progress=True
  .github/workflows/main.yml
Labels: CI

#210 Implement pydantic models as dataclasses
  ci/environment.yml
  docs/releases.rst
  pyproject.toml
  virtualizarr/manifests/manifest.py
  virtualizarr/tests/test_kerchunk.py
  virtualizarr/tests/test_manifests/test_manifest.py
  virtualizarr/tests/test_zarr.py
  virtualizarr/zarr.py
Labels: dependencies

#223 use the theme options for `pydata_sphinx_theme`
  docs/conf.py
Labels: documentation

#228 Removes default storage options
  virtualizarr/kerchunk.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/utils.py
  virtualizarr/xarray.py
Labels: remote files

#113 open_virtual_dataset with dmr++
  docs/releases.rst
  virtualizarr/kerchunk.py
  virtualizarr/readers/dmrpp.py
  virtualizarr/tests/test_readers/test_dmrpp.py
  virtualizarr/utils.py
  virtualizarr/xarray.py
Labels: enhancement, references generation

#232 Let Xarray handle `decode_times`
  docs/releases.rst
  docs/usage.md
  virtualizarr/backend.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_integration.py
Labels: encoding, CF conventions

#165 Support specifying single HDF Group in open_virtual_dataset
  conftest.py
  docs/releases.rst
  virtualizarr/backend.py
  virtualizarr/readers/kerchunk.py
  virtualizarr/tests/test_backend.py
  virtualizarr/types/kerchunk.py
Labels: enhancement, references generation

#234 Adds defaults in `open_virtual_dataset_from_v3_store`
  docs/releases.rst
  virtualizarr/readers/zarr.py
Labels: typing

#233 Virtualizarr + Coiled Serverless Example Notebook
  docs/releases.rst
  examples/coiled/terraclimate.ipynb
Labels: usage example
