Repository zarr-developers/VirtualiZarr, pull requests merged in 2024-06, with the labels that each got.

#136 Add release workflow
  .github/workflows/release.yml
  .gitignore
  docs/contributing.md
  docs/index.md
  pyproject.toml
Labels: Packaging

#139 Hypothesis test broadcasting
  pyproject.toml
  virtualizarr/tests/__init__.py
  virtualizarr/tests/test_manifests/test_array.py
Labels: testing

#148 Install dependencies for tests via mamba
  .github/workflows/main.yml
  ci/environment.yml
Labels: CI

#149 Use default version scheme for setuptools_scm
  .github/workflows/release.yml
  pyproject.toml
Labels: Packaging

#107 Use 3 numpy arrays for manifest internally
  ci/environment.yml
  docs/releases.rst
  pyproject.toml
  virtualizarr/kerchunk.py
  virtualizarr/manifests/__init__.py
  virtualizarr/manifests/array.py
  virtualizarr/manifests/array_api.py
  virtualizarr/manifests/manifest.py
  virtualizarr/tests/test_kerchunk.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_manifests/test_manifest.py
  virtualizarr/tests/test_zarr.py
  virtualizarr/zarr.py
Labels: enhancement, performance

#152 Rename paths in manifest
  docs/api.rst
  docs/releases.rst
  docs/usage.md
  virtualizarr/manifests/array.py
  virtualizarr/manifests/manifest.py
  virtualizarr/tests/test_manifests/test_manifest.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/xarray.py
Labels: enhancement

#153 Ensure _ARRAY_DIMENSIONS get dropped from attrs
  docs/releases.rst
  virtualizarr/tests/test_xarray.py
  virtualizarr/xarray.py
Labels: bug

#154 Ensure attributes on coordinate variables are preserved during round-tripping
  docs/releases.rst
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/xarray.py
Labels: bug

#156 Identify non dimension coords
  docs/releases.rst
  virtualizarr/kerchunk.py
  virtualizarr/tests/test_integration.py
  virtualizarr/xarray.py
Labels: CF conventions

#158 Also test exporting references to in-memory kerchunk reference dict
  virtualizarr/tests/test_integration.py
Labels: testing

#143 Use magic bytes to identify file formats
  docs/contributing.md
  docs/releases.rst
  pyproject.toml
  virtualizarr/kerchunk.py
  virtualizarr/tests/test_kerchunk.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/xarray.py
Labels: references generation

#122 Decoding `cftime_variables`
  docs/releases.rst
  virtualizarr/kerchunk.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/xarray.py
Labels: encoding
