Repository zarr-developers/VirtualiZarr, pull requests merged in 2025-03, with the labels that each got.

#456 Store -> Datacube language in readme
  README.md
Labels: documentation

#462 Update minimum icechunk version to v0.2.4
  ci/environment.yml
  ci/upstream.yml
  docs/releases.rst
  pyproject.toml
Labels: dependencies, Icechunk :ice_cube:

#461 Add missing pytest-asyncio plugin
  ci/environment.yml
Labels: testing

#463 Release notes for v1.3.2
  docs/releases.rst
Labels: documentation, releases

#464 Empty release notes for next version
  docs/releases.rst
Labels: releases

#469 Use context managers in test functions
  conftest.py
  virtualizarr/backend.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_readers/conftest.py
  virtualizarr/tests/test_readers/test_hdf/test_hdf_integration.py
  virtualizarr/tests/test_xarray.py
Labels: testing

#475 Add mursst lithops example
  docs/examples.md
  docs/releases.rst
  examples/mursst-icechunk-with-lithops/Dockerfile
  examples/mursst-icechunk-with-lithops/README.md
  examples/mursst-icechunk-with-lithops/__init__.py
  examples/mursst-icechunk-with-lithops/cli.py
  examples/mursst-icechunk-with-lithops/config.py
  examples/mursst-icechunk-with-lithops/ec2_for_lithops_runtime/00-create-security-group.sh
  examples/mursst-icechunk-with-lithops/ec2_for_lithops_runtime/01-launch-ec2.sh
  examples/mursst-icechunk-with-lithops/ec2_for_lithops_runtime/02-setup-ec2-role.sh
  examples/mursst-icechunk-with-lithops/ec2_for_lithops_runtime/03-setup-ec2.sh
  examples/mursst-icechunk-with-lithops/ec2_for_lithops_runtime/README.md
  examples/mursst-icechunk-with-lithops/helpers.py
  examples/mursst-icechunk-with-lithops/lithops.yaml
  examples/mursst-icechunk-with-lithops/lithops_functions.py
  examples/mursst-icechunk-with-lithops/main.py
  examples/mursst-icechunk-with-lithops/models.py
  examples/mursst-icechunk-with-lithops/repo.py
  examples/mursst-icechunk-with-lithops/requirements.txt
  examples/mursst-icechunk-with-lithops/url_utils.py
  examples/mursst-icechunk-with-lithops/virtual_datasets.py
  examples/mursst-icechunk-with-lithops/zarr_operations.py
Labels: usage example

#483 Typo in usage docs
  docs/usage.md
Labels: documentation

#407 Manage dependencies with pixi
  .github/workflows/main.yml
  .github/workflows/min-deps.yml
  .github/workflows/typing.yml
  .github/workflows/upstream.yml
  .gitignore
  .readthedocs.yml
  ci/doc.yml
  ci/environment.yml
  ci/min-deps.yml
  ci/upstream.yml
  docs/contributing.md
  docs/releases.rst
  pyproject.toml
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_readers/test_hdf/test_hdf_filters.py
Labels: CI, dependencies

#493 Fix broken and outdated references
  docs/usage.md
  virtualizarr/manifests/array_api.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_readers/test_kerchunk.py
  virtualizarr/tests/test_xarray.py
Labels: documentation

#494 List all installed libraries in CI
  .github/workflows/main.yml
  .github/workflows/typing.yml
Labels: CI

#503 Setup intersphinx mapping for docs
  docs/conf.py
Labels: documentation

#477 Change default loadable_variables (and indexes) to match xarray's behaviour
  conftest.py
  docs/releases.rst
  docs/usage.md
  virtualizarr/backend.py
  virtualizarr/readers/api.py
  virtualizarr/readers/common.py
  virtualizarr/readers/dmrpp.py
  virtualizarr/readers/fits.py
  virtualizarr/readers/hdf/__init__.py
  virtualizarr/readers/hdf/hdf.py
  virtualizarr/readers/hdf5.py
  virtualizarr/readers/kerchunk.py
  virtualizarr/readers/netcdf3.py
  virtualizarr/readers/tiff.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_readers/test_dmrpp.py
  virtualizarr/tests/test_readers/test_hdf/test_hdf.py
  virtualizarr/tests/test_readers/test_kerchunk.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/translators/kerchunk.py
  virtualizarr/writers/kerchunk.py
Labels: internals

#504 Update pyproject.toml deps
  pyproject.toml
Labels: dependencies

#506 Use pytest-xdist to distribute tests across CPUs
  pyproject.toml
Labels: CI, testing

#490 Add ManifestStore for loading data from ManifestArrays
  docs/conf.py
  docs/releases.rst
  pyproject.toml
  virtualizarr/manifests/__init__.py
  virtualizarr/manifests/group.py
  virtualizarr/manifests/store.py
  virtualizarr/tests/__init__.py
  virtualizarr/tests/test_manifests/test_group.py
  virtualizarr/tests/test_manifests/test_store.py
  virtualizarr/vendor/zarr/metadata.py
Labels: enhancement

#507 Test ManifestStore against S3 and fix key parsing
  .github/workflows/main.yml
  conftest.py
  pyproject.toml
  virtualizarr/manifests/store.py
  virtualizarr/tests/__init__.py
  virtualizarr/tests/conftest.py
  virtualizarr/tests/test_manifests/test_store.py
Labels: bug, CI, testing

#512 Simplify hdf5 typing
  pyproject.toml
  virtualizarr/readers/hdf/hdf.py
Labels: typing

#349 Add open_virtual_mfdataset
  docs/releases.rst
  pyproject.toml
  virtualizarr/__init__.py
  virtualizarr/backend.py
  virtualizarr/manifests/store.py
  virtualizarr/parallel.py
  virtualizarr/tests/__init__.py
  virtualizarr/tests/test_backend.py
Labels: enhancement

#518 Refactor ManifestGroup
  virtualizarr/manifests/__init__.py
  virtualizarr/manifests/group.py
  virtualizarr/manifests/store.py
  virtualizarr/tests/test_manifests/test_group.py
  virtualizarr/tests/test_manifests/test_store.py
Labels: internals
