Repository zarr-developers/VirtualiZarr, pull requests merged in 2025-04, with the labels that each got.

#522 Add methods to create virtual dataset from manifeststore
  conftest.py
  docs/releases.rst
  virtualizarr/common.py
  virtualizarr/manifests/array.py
  virtualizarr/manifests/group.py
  virtualizarr/manifests/store.py
  virtualizarr/manifests/utils.py
  virtualizarr/readers/fits.py
  virtualizarr/readers/hdf/hdf.py
  virtualizarr/readers/hdf5.py
  virtualizarr/readers/netcdf3.py
  virtualizarr/readers/tiff.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_manifests/test_group.py
  virtualizarr/tests/test_manifests/test_store.py
  virtualizarr/tests/test_writers/test_icechunk.py
  virtualizarr/translators/kerchunk.py
Labels: internals

#532 add faq answer on virtualizing data
  docs/faq.md
  docs/releases.rst
Labels: documentation

#538 Support writing xarray.DataTree to Icechunk store
  docs/api.rst
  docs/releases.rst
  virtualizarr/__init__.py
  virtualizarr/accessor.py
  virtualizarr/tests/test_integration.py
  virtualizarr/writers/icechunk.py
Labels: enhancement

#543 Add loadable_variables kwarg to ManifestStore.to_virtual_dataset()
  docs/releases.rst
  virtualizarr/common.py
  virtualizarr/manifests/group.py
  virtualizarr/manifests/store.py
  virtualizarr/readers/fits.py
  virtualizarr/readers/hdf/hdf.py
  virtualizarr/readers/hdf5.py
  virtualizarr/readers/netcdf3.py
  virtualizarr/readers/tiff.py
  virtualizarr/tests/test_manifests/test_store.py
  virtualizarr/tests/test_writers/test_icechunk.py
  virtualizarr/translators/kerchunk.py
  virtualizarr/xarray.py
Labels: internals

#563 Separate understanding (data models) from learning (usage) in docs
  .gitignore
  .pre-commit-config.yaml
  docs/data_structures.md
  docs/faq.md
  docs/index.md
  docs/installation.md
  docs/releases.rst
  docs/usage.md
  examples/coiled/terraclimate.ipynb
  examples/mursst-icechunk-with-lithops/README.md
  examples/mursst-icechunk-with-lithops/ec2_for_lithops_runtime/README.md
  virtualizarr/manifests/array_api.py
  virtualizarr/manifests/manifest.py
  virtualizarr/readers/dmrpp.py
  virtualizarr/readers/kerchunk.py
  virtualizarr/tests/test_writers/test_icechunk.py
Labels: documentation

#271 Zarr reader
  conftest.py
  docs/faq.md
  docs/releases.rst
  virtualizarr/backend.py
  virtualizarr/codecs.py
  virtualizarr/manifests/manifest.py
  virtualizarr/manifests/store.py
  virtualizarr/readers/__init__.py
  virtualizarr/readers/zarr.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_readers/test_zarr.py
  virtualizarr/utils.py
  virtualizarr/vendor/__init__.py
  virtualizarr/vendor/zarr/__init__.py
  virtualizarr/vendor/zarr/core/__init__.py
  virtualizarr/vendor/zarr/core/common.py
  virtualizarr/vendor/zarr/core/metadata.py
  virtualizarr/xarray.py
Labels: zarr-python, readers

#572 Test 2d combine
  conftest.py
  virtualizarr/tests/test_xarray.py
Labels: testing

#577 Make the supported and non-supported filetypes clearer in the FAQ
  docs/faq.md
Labels: documentation
