Repository zarr-developers/VirtualiZarr, pull requests merged in 2025-02, with the labels that each got.

#412 Update to zarr-v3-compatible released version of Kerchunk (0.2.8)
  .github/workflows/main.yml
  ci/environment.yml
  docs/releases.rst
  pyproject.toml
Labels: Kerchunk, dependencies

#309 Split optional dependencies in pyproject.toml
  docs/installation.md
  docs/releases.rst
  pyproject.toml
Labels: Packaging, dependencies

#419 Update Icechunk dependency to v0.1.1
  ci/environment.yml
  ci/upstream.yml
  docs/releases.rst
  pyproject.toml
Labels: dependencies, Icechunk :ice_cube:

#425 Install Icechunk from Conda in CI
  ci/environment.yml
Labels: CI, Icechunk :ice_cube:

#431 Updates examples to newer Icechunk syntax
  docs/usage.md
  examples/append/noaa-cdr-sst.ipynb
  examples/coiled/terraclimate.ipynb
Labels: documentation, Icechunk :ice_cube:

#429 Manifest arrays use arrayv3metadata
  ci/environment.yml
  ci/min-deps.yml
  ci/upstream.yml
  conftest.py
  docs/releases.rst
  docs/usage.md
  pyproject.toml
  virtualizarr/codecs.py
  virtualizarr/manifests/array.py
  virtualizarr/manifests/array_api.py
  virtualizarr/manifests/utils.py
  virtualizarr/readers/dmrpp.py
  virtualizarr/readers/hdf/hdf.py
  virtualizarr/tests/__init__.py
  virtualizarr/tests/test_backend.py
  virtualizarr/tests/test_codecs.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_readers/test_dmrpp.py
  virtualizarr/tests/test_readers/test_fits.py
  virtualizarr/tests/test_readers/test_kerchunk.py
  virtualizarr/tests/test_readers/test_netcdf3.py
  virtualizarr/tests/test_utils.py
  virtualizarr/tests/test_writers/conftest.py
  virtualizarr/tests/test_writers/test_icechunk.py
  virtualizarr/tests/test_writers/test_kerchunk.py
  virtualizarr/tests/test_xarray.py
  virtualizarr/tests/test_zarr.py
  virtualizarr/translators/kerchunk.py
  virtualizarr/utils.py
  virtualizarr/writers/icechunk.py
  virtualizarr/writers/kerchunk.py
  virtualizarr/zarr.py
Labels: zarr-python, internals

#443 Update `store.set_virtual_ref` -> `store.set_virtual_refs`
  docs/releases.rst
  virtualizarr/tests/test_writers/test_icechunk.py
  virtualizarr/writers/icechunk.py
Labels: enhancement, performance, internals, Icechunk :ice_cube:
