Repository zarr-developers/VirtualiZarr, pull requests merged in 2025-06, with the labels that each got.

#615 Use mkdocs-material for documentation
  .gitignore
  docs/Makefile
  docs/_static/custom.css
  docs/api.md
  docs/api.rst
  docs/conf.py
  docs/contributing.md
  docs/core_team_guide.md
  docs/custom_readers.md
  docs/data_structures.md
  docs/examples.md
  docs/faq.md
  docs/index.md
  docs/installation.md
  docs/make.bat
  docs/overrides/main.html
  docs/overrides/stylesheets/extra.css
  docs/releases.md
  docs/releases.rst
  docs/usage.md
  mkdocs.yml
  pyproject.toml
  virtualizarr/accessor.py
  virtualizarr/manifests/array.py
  virtualizarr/manifests/manifest.py
  virtualizarr/xarray.py
Labels: documentation, CI

#590 Docs on `open_virtual_mfdataset` and scaling
  docs/api.md
  docs/releases.md
  docs/scaling.md
  docs/usage.md
  examples/oae/Dockerfile
  examples/oae/README.md
  mkdocs.yml
  virtualizarr/parallel.py
  virtualizarr/xarray.py
Labels: documentation, enhancement, performance

#480 Make virtual chunk staleness check opt out
  docs/releases.md
  virtualizarr/accessor.py
  virtualizarr/tests/test_writers/test_icechunk.py
  virtualizarr/writers/icechunk.py
Labels: Icechunk :ice_cube:

#566 Add ManifestGroup, ManifestStore and ObjectStoreRegistry to the docs
  docs/api.md
  virtualizarr/manifests/group.py
  virtualizarr/manifests/store.py
Labels: documentation

#633 Move `virtualizarr.translators` module to inside new `virtualizarr.parsers.kerchunk` module
  docs/releases.md
  virtualizarr/parsers/__init__.py
  virtualizarr/parsers/fits.py
  virtualizarr/parsers/kerchunk/__init__.py
  virtualizarr/parsers/kerchunk/json.py
  virtualizarr/parsers/kerchunk/parquet.py
  virtualizarr/parsers/kerchunk/translator.py
  virtualizarr/parsers/netcdf3.py
  virtualizarr/parsers/tiff.py
  virtualizarr/tests/test_integration.py
  virtualizarr/writers/kerchunk.py
Labels: internals

#642 Test against minimum supported version of dependencies
  .github/workflows/upstream.yml
  pyproject.toml
Labels: CI, test-upstream
