Repository zarr-developers/VirtualiZarr, pull requests merged in 2025-07, with the labels that each got.

#637 adds v1->v2 migration guide docs
  docs/migration_guide.md
  docs/releases.md
  mkdocs.yml
Labels: documentation

#641 Allow concatenating empty variables
  docs/releases.md
  virtualizarr/manifests/array.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_xarray.py
Labels: bug

#677 Zarr data types refactor compat round 2
  docs/releases.md
  pyproject.toml
  virtualizarr/manifests/array.py
  virtualizarr/manifests/utils.py
  virtualizarr/tests/test_integration.py
  virtualizarr/tests/test_manifests/test_array.py
  virtualizarr/tests/test_parsers/test_dmrpp.py
  virtualizarr/tests/test_writers/test_kerchunk.py
  virtualizarr/utils.py
  virtualizarr/writers/icechunk.py
  virtualizarr/writers/kerchunk.py
Labels: zarr-python, dependencies

#705 Pin xarray to 2025.06.0
  pyproject.toml
Labels: test-upstream

#701 Updating usage doc to v2
  docs/index.md
  docs/usage.md
Labels: documentation

#734 Refactor indexing
  docs/releases.md
  virtualizarr/manifests/array.py
  virtualizarr/manifests/indexing.py
  virtualizarr/tests/test_manifests/test_array.py
Labels: testing, internals

#745 Don't write empty chunks to icechunk
  docs/releases.md
  virtualizarr/tests/test_writers/test_icechunk.py
  virtualizarr/writers/icechunk.py
Labels: Icechunk :ice_cube:
